# Generated by Django 3.2.6 on 2023-08-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_auto_20230823_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платежка', 'verbose_name_plural': 'Платежка'},
        ),
        migrations.RemoveField(
            model_name='bot',
            name='referal_percentage',
        ),
        migrations.AddField(
            model_name='bot',
            name='damps_percentage',
            field=models.IntegerField(default=0, verbose_name='Дампы рефералов'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='admins',
            field=models.CharField(help_text='Через запятую без пробела', max_length=1000, verbose_name='Админы'),
        ),
    ]
