# Generated by Django 3.2.6 on 2023-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_alltext_by_ref_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='damps_percentage',
            field=models.ImageField(upload_to='Files/links', verbose_name='Дампы рефералов'),
        ),
    ]
