# Generated by Django 3.2.6 on 2023-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0005_alter_bot_damps_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='damps_percentage',
            field=models.ImageField(upload_to='Files/links//ref_links.txt', verbose_name='Дампы рефералов'),
        ),
    ]
