# Generated by Django 3.2.6 on 2023-08-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_remove_alltext_by_ref_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ref_link',
            field=models.IntegerField(default=0, verbose_name='Кол-во ссылок'),
        ),
    ]
