# Generated by Django 3.2.6 on 2023-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_users_ref_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltext',
            name='ref_text',
            field=models.TextField(help_text='"Реф.Система" | %ref% | %bal% | %link% | %links%', max_length=4024, verbose_name='Рефка'),
        ),
    ]
