# Generated by Django 3.2.6 on 2023-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0011_alter_alltext_ref_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesetting',
            name='watermark',
            field=models.ImageField(upload_to='Files/Photos/', verbose_name='Watermark'),
        ),
    ]
