# Generated by Django 3.2.6 on 2023-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0012_alter_templatesetting_watermark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesetting',
            name='watermark',
            field=models.ImageField(upload_to='Files/Photos', verbose_name='Watermark'),
        ),
    ]
