# Generated by Django 3.2.6 on 2023-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0015_alter_bot_vk_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='links',
            field=models.FileField(upload_to='links', verbose_name='Коллаж'),
        ),
    ]
