# Generated by Django 3.2.6 on 2023-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0016_alter_links_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_search_link',
            field=models.IntegerField(default=0),
        ),
    ]
