# Generated by Django 3.2.6 on 2023-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0017_users_last_search_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_search_link',
            field=models.TextField(default='0'),
        ),
    ]
