# Generated by Django 3.2.6 on 2023-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0019_remove_users_last_search_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_search_link',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
