# Generated by Django 3.2.6 on 2023-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0020_users_last_search_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltext',
            name='text_notification',
            field=models.TextField(default=1, help_text='Стандартный текст уведомления', max_length=4024, verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
