# Generated by Django 3.2.6 on 2023-09-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0021_alltext_text_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='google_token',
            field=models.CharField(default=1, max_length=100, verbose_name='Google токен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alltext',
            name='text_notification',
            field=models.TextField(help_text='Стандартный текст уведомления. %LN% - Last Name | %FN% - First Name | %ID% - ID', max_length=4024, verbose_name='Рассылка'),
        ),
    ]
